nav:
  Home: /
  Archives: /blog/archives/
  Github: http://github.com/dharFr

projects_url: https://github.com/dharFr?tab=repositories

customize:
    gravatar:
        email: audard@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url:
        # url: http://www.gravatar.com/avatar/cb972f1f26bcba62452abaaae6845e6a?s=50
        gravatar: true
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /favicon.png
        gravatar: true
      android:
        # url: /images/favicon-192x192.png
        gravator: true
      apple:
        # url: /images/apple-touch-icon.png
        gravator: true
    social_links:
        twitter: http://twitter.com/_dhar
        github: http://github.com/dharFr
        linkedin: https://www.linkedin.com/in/audard
        stack-overflow: http://stackoverflow.com/users/447446/dhar
        dailymotion: https://www.dailymotion.com/dharfr
    post_count: 5
    highlight: rainbow

# RSS
rss:

# Plugins
plugins:
    disqus_shortname: dhar
    google_analytics: UA-1823374-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id: _dhar
    google_plus:
